version: '2.1'
services:
  ids:
    container_name: 'client'
    command: ./docker/client.sh
    image: robotattack
    volumes:
      - ../:/tmp
    environment:
      - "PYTHONUNBUFFERED=1"
    networks:
      frontend:
        ipv4_address: 10.0.1.20

  server: 
    container_name: 'server'
    command: ''
    image: erlang-server
    logging:
      driver: "none"
    volumes:
      - ./:/tmp
    environment:
      - "PYTHONUNBUFFERED=1"
    networks:
      frontend:
        ipv4_address: 10.0.1.30

networks:
  frontend:
    driver: bridge
    ipam:
      config:
      -
        subnet: 10.0.1.0/24
  backend:
    driver: bridge
    ipam:
      config:
      -
        subnet: 10.0.2.0/24

